### ISSUE TITLE
User can search for movie titles

### ISSUE THREAD

**Issue by OSAdams** [OSAdams/Movie-Review#1]
## 💰 Motivation
People should be able to see information about a movie and have discussions based on the movie!

## 📐 Plan
Create a search feature so users can search for a movie.

## 🖼️ Wireframe
![image](https://user-images.githubusercontent.com/76730244/113946279-fc339800-97d5-11eb-8fef-2d0894653665.png)

## ✅ Task List
- [x] Add stylesheets and fonts to HTML Document
- [x] Add background color to styling
- [x] Create a navigation bar document
- [x] Style the navigation bar
- [x] Add a menu icon and the title to the navigation bar
- [x] Add and style the logo
- [x] Add the text "Search by Title!"
- [x] Add a text input for the Search box
- [x] Add a Search button
- [x] Add functionality to the search button that will take the search value and remove spaces with '+'
- [x] Add functionality to the search button that will fetch an API and modify the API URL string to use the modified search value
- [x] console.log the object make sure you're getting the correct data for movie links
- [x] Test the functionality of the search button with multiple movies

**Comment by OSAdams** [comment]
![image](https://user-images.githubusercontent.com/76730244/114253084-95011980-9976-11eb-9d3e-d2f38321f3f9.png)
