### ISSUE TITLE
Refactor styling

### ISSUE THREAD

**Issue by OSAdams** [OSAdams/Movie-Review#14]
## 💰 Motivation
If styling can be used globally, it needs to be in the styles.css file. If there is a strict one time usage, use it in the React file.

## 📐 Plan
Add a bar with emoticons that will update the text input form when you click on a specific emoticon.

## 🖼️ Wireframe
![image](https://user-images.githubusercontent.com/76730244/114945117-c8302680-9e16-11eb-9367-7007f2a4f901.png)

## ✅ Task List
- [x] Move and refactor CSS
- [x] Modify class names where necessary in the DOM of react files
- [x] Move the title of the movie to be above the movie information
- [x] Test all CSS, remove styling that isn't doing anything
- [x] Test functionality with multiple movie titles
