### ISSUE TITLE
User can see a movie image and the plot

### ISSUE THREAD

**Issue by OSAdams** [OSAdams/Movie-Review#2]
## 💰 Motivation
People should be able to see information about a movie and have discussions based on the movie!

## 📐 Plan
Pull information from an API to display an image and the plot of the movie.

## 🖼️ Wireframe
![image](https://user-images.githubusercontent.com/76730244/114064553-c4753080-9867-11eb-9fea-246534ffcd9b.png)

## ✅ Task List
- [x] Create a parse-route.js file
- [x] Define and export praseRoute function to hash the displayed page
- [x] In app.jsx, define a componentDidMount method
- [x] Add a window event listener for a hashchange
- [x] Set the State to the route variable
- [x] Define a renderPage method
- [x] Destructure the route to the state
- [x] If there is no route path, return the Home page
- [x] If there is a route path of 'search-results', define a variable to the route.params.get('title')
- [x] Return the DisplayMovie page with the userInputValue assigned the title
- [x] Modify the render method to inclue this.renderPage()
- [x] Create a search-result.jsx file
- [x] Import React
- [x] In search-result.jsx file, define the DisplayMovies class
- [x] Set the state to movie: null
- [x] Define a componentDidMount method
- [x] Add a fetch call to the definition modifying the fetch link with the movie title (this.props.userInputValue)
- [x] Then, convert the response to JSON
- [x] Then, set the state to { movie }
- [x] Define the render method
- [x] Destructure the this.state.movie from Title, Movie, and Poster
- [x] Add columns and rows that will hold the Movie Data
- [x] Create elements that will hold the movie information
- [x] Add Poster to an img src
- [x] Add Title to a div that will display the Title of the movie
- [x] Add Plot to a div that will display the Plot of the movie
- [x] Add styling to all elements to match wireframe
- [x] Test functionality
