### ISSUE TITLE
User can see detailed information about the movie

### ISSUE THREAD

**Issue by OSAdams** [OSAdams/Movie-Review#5]
## 💰 Motivation
The user will see information such as Box Office Revenue, the Director, the Rating, the Runtime, and the year the movie was released.

## 📐 Plan
Pull information from an API and list the movie information to the right of the movie image.

## 🖼️ Wireframe
![image](https://user-images.githubusercontent.com/76730244/114064553-c4753080-9867-11eb-9fea-246534ffcd9b.png)

## ✅ Task List
- [x] Change styling in navigation bar component and search-result page to better reflect the Wireframe
- [x] Destructure this.state.movie for Genre, Rated, BoxOffice, Director, RunTime, and Release
- [x] Create div elements that will contain a label for the movie information
- [x] Create spans inside of created div elements
- [x] Left span will contain label
- [x] Right span will contain data
- [x] Add styling to match figma
- [x] Destructure this.state.movie for Ratings: IMDB, Metacritic, and Rotten Tomato
- [x] Test functionality with multiple movies
