### ISSUE TITLE
User can write a review for a movie

### ISSUE THREAD

**Issue by OSAdams** [OSAdams/Movie-Review#6]
## 💰 Motivation
People like to discuss movies. They discuss theories, plot holes, character development, and more!

## 📐 Plan
Create a user input form that will allow users to write a review for a movie!

## 🖼️ Wireframe
![image](https://user-images.githubusercontent.com/76730244/114065276-7ad91580-9868-11eb-9a44-e02cc501f8ba.png)

## ✅ Task List
- [x] Create a component that will render a form input for the user to write a view
- [x] Import component to the search-result page
- [x] Add appropriate styling
- [x] Update styling for home page
- [x] Create a handleChange event handler for the text area input
- [x] update this.state in the user-input react file
- [x] Create a handleSubmit event handler for the submit button for the text area
- [x] Test functionality
